#development:
# adapter: mysql2
# encoding: utf8
# reconnect: false
# host: localhost
# database: stweet-app
# pool: 5
# username: root
# password: root

 production:
   adapter: postgresql
   encoding: unicode
   database: stweet
   pool: 5
   host: localhost
   username: pguser-name
   password: pguser-name
